'#pragma once' 
'#include "IFigure2D.h"' 
'' 
'class Triangle : public IFigure2D {' 
'private:' 
'    double base;' 
'    double height;' 
'public:' 
'    Triangle(double b, double h);' 
'    void square() override;' 
'};' 
